<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="21" passed="19" failed="2" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2021-03-25T20:01:32 IST" name="Suite" finished-at="2021-03-25T20:08:11 IST" duration-ms="398828">
    <groups>
    </groups>
    <test started-at="2021-03-25T20:01:32 IST" name="Test" finished-at="2021-03-25T20:08:11 IST" duration-ms="398828">
      <class name="com.practo.tests.TestCases">
        <test-method is-config="true" signature="getDriver()[pri:0, instance:com.practo.tests.TestCases@4cc8eb05]" started-at="2021-03-25T20:01:27 IST" name="getDriver" finished-at="2021-03-25T20:01:32 IST" duration-ms="5031" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- getDriver -->
        <test-method signature="TC_FH_001()[pri:0, instance:com.practo.tests.TestCases@4cc8eb05]" started-at="2021-03-25T20:01:32 IST" name="TC_FH_001" finished-at="2021-03-25T20:01:42 IST" duration-ms="9098" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TC_FH_001 -->
        <test-method signature="TC_FH_002()[pri:1, instance:com.practo.tests.TestCases@4cc8eb05]" started-at="2021-03-25T20:01:42 IST" name="TC_FH_002" finished-at="2021-03-25T20:01:58 IST" duration-ms="16024" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TC_FH_002 -->
        <test-method signature="TC_FH_003()[pri:2, instance:com.practo.tests.TestCases@4cc8eb05]" started-at="2021-03-25T20:01:58 IST" name="TC_FH_003" finished-at="2021-03-25T20:02:16 IST" duration-ms="18868" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TC_FH_003 -->
        <test-method signature="TC_FH_004()[pri:3, instance:com.practo.tests.TestCases@4cc8eb05]" started-at="2021-03-25T20:02:16 IST" name="TC_FH_004" finished-at="2021-03-25T20:02:40 IST" duration-ms="23671" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TC_FH_004 -->
        <test-method signature="TC_FH_005()[pri:4, instance:com.practo.tests.TestCases@4cc8eb05]" started-at="2021-03-25T20:02:40 IST" name="TC_FH_005" finished-at="2021-03-25T20:02:53 IST" duration-ms="13297" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TC_FH_005 -->
        <test-method signature="TC_FH_006()[pri:5, instance:com.practo.tests.TestCases@4cc8eb05]" started-at="2021-03-25T20:02:53 IST" name="TC_FH_006" finished-at="2021-03-25T20:03:21 IST" duration-ms="27339" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TC_FH_006 -->
        <test-method signature="TC_FH_007()[pri:6, instance:com.practo.tests.TestCases@4cc8eb05]" started-at="2021-03-25T20:03:21 IST" name="TC_FH_007" finished-at="2021-03-25T20:03:45 IST" duration-ms="24128" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TC_FH_007 -->
        <test-method signature="TC_FH_008()[pri:7, instance:com.practo.tests.TestCases@4cc8eb05]" started-at="2021-03-25T20:03:45 IST" name="TC_FH_008" finished-at="2021-03-25T20:05:33 IST" duration-ms="108493" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TC_FH_008 -->
        <test-method signature="TC_FH_009()[pri:8, instance:com.practo.tests.TestCases@4cc8eb05]" started-at="2021-03-25T20:05:33 IST" name="TC_FH_009" finished-at="2021-03-25T20:05:51 IST" duration-ms="17634" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TC_FH_009 -->
        <test-method signature="TC_FH_010()[pri:9, instance:com.practo.tests.TestCases@4cc8eb05]" started-at="2021-03-25T20:05:51 IST" name="TC_FH_010" finished-at="2021-03-25T20:05:57 IST" duration-ms="5923" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TC_FH_010 -->
        <test-method signature="TC_FH_011()[pri:10, instance:com.practo.tests.TestCases@4cc8eb05]" started-at="2021-03-25T20:05:57 IST" name="TC_FH_011" finished-at="2021-03-25T20:06:10 IST" duration-ms="13139" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TC_FH_011 -->
        <test-method signature="TC_FH_012()[pri:11, instance:com.practo.tests.TestCases@4cc8eb05]" started-at="2021-03-25T20:06:10 IST" name="TC_FH_012" finished-at="2021-03-25T20:06:23 IST" duration-ms="12690" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TC_FH_012 -->
        <test-method signature="TC_FH_013()[pri:12, instance:com.practo.tests.TestCases@4cc8eb05]" started-at="2021-03-25T20:06:23 IST" name="TC_FH_013" finished-at="2021-03-25T20:06:33 IST" duration-ms="9889" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TC_FH_013 -->
        <test-method signature="TC_FH_014()[pri:13, instance:com.practo.tests.TestCases@4cc8eb05]" started-at="2021-03-25T20:06:33 IST" name="TC_FH_014" finished-at="2021-03-25T20:06:43 IST" duration-ms="9895" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TC_FH_014 -->
        <test-method signature="TC_FH_015()[pri:14, instance:com.practo.tests.TestCases@4cc8eb05]" started-at="2021-03-25T20:06:43 IST" name="TC_FH_015" finished-at="2021-03-25T20:06:54 IST" duration-ms="10952" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TC_FH_015 -->
        <test-method signature="TC_FH_016()[pri:15, instance:com.practo.tests.TestCases@4cc8eb05]" started-at="2021-03-25T20:06:54 IST" name="TC_FH_016" finished-at="2021-03-25T20:07:05 IST" duration-ms="11611" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TC_FH_016 -->
        <test-method signature="TC_FH_017()[pri:16, instance:com.practo.tests.TestCases@4cc8eb05]" started-at="2021-03-25T20:07:05 IST" name="TC_FH_017" finished-at="2021-03-25T20:07:24 IST" duration-ms="18973" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TC_FH_017 -->
        <test-method signature="TC_FH_018()[pri:17, instance:com.practo.tests.TestCases@4cc8eb05]" started-at="2021-03-25T20:07:24 IST" name="TC_FH_018" finished-at="2021-03-25T20:07:41 IST" duration-ms="16408" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TC_FH_018 -->
        <test-method signature="TC_FH_019()[pri:18, instance:com.practo.tests.TestCases@4cc8eb05]" started-at="2021-03-25T20:07:41 IST" name="TC_FH_019" finished-at="2021-03-25T20:07:50 IST" duration-ms="9001" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TC_FH_019 -->
        <test-method signature="TC_FH_020()[pri:19, instance:com.practo.tests.TestCases@4cc8eb05]" started-at="2021-03-25T20:07:50 IST" name="TC_FH_020" finished-at="2021-03-25T20:08:00 IST" duration-ms="10273" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertTrue(Assert.java:45)
at org.testng.Assert.assertTrue(Assert.java:55)
at com.practo.tests.TestCases.TC_FH_020(TestCases.java:724)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:564)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:822)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:764)
at org.testng.TestRunner.run(TestRunner.java:585)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1218)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
at org.testng.TestNG.runSuites(TestNG.java:1069)
at org.testng.TestNG.run(TestNG.java:1037)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TC_FH_020 -->
        <test-method signature="TC_FH_021()[pri:20, instance:com.practo.tests.TestCases@4cc8eb05]" started-at="2021-03-25T20:08:00 IST" name="TC_FH_021" finished-at="2021-03-25T20:08:11 IST" duration-ms="11296" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertTrue(Assert.java:45)
at org.testng.Assert.assertTrue(Assert.java:55)
at com.practo.tests.TestCases.TC_FH_021(TestCases.java:754)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:564)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:822)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:764)
at org.testng.TestRunner.run(TestRunner.java:585)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1218)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
at org.testng.TestNG.runSuites(TestNG.java:1069)
at org.testng.TestNG.run(TestNG.java:1037)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TC_FH_021 -->
        <test-method is-config="true" signature="quitDriver()[pri:0, instance:com.practo.tests.TestCases@4cc8eb05]" started-at="2021-03-25T20:08:11 IST" name="quitDriver" finished-at="2021-03-25T20:08:16 IST" duration-ms="5160" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- quitDriver -->
      </class> <!-- com.practo.tests.TestCases -->
    </test> <!-- Test -->
  </suite> <!-- Suite -->
</testng-results>
